### ISSUE TITLE
revert to pre-Ryan changes 

### ISSUE THREAD

**Issue by stidhamjason** [jadmr/cpts483_Summer2015_drc#3]
this will correct 2 things,  
1. DB does not include Admin
2. Monthly Report does not count Children or people served.

**Comment by jadmr** [comment]
We'll work out the details later, but we basically have two options: revert or comb through and manually revert the changes. The latter may be more appealing since weve commited a few things. Shouldnt be too hard

**Comment by jadmr** [comment]
Fixed on my build, need to push out the changes

**Comment by jadmr** [comment]
Changes reverted
